name: Super-Auto-Spider
on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:
jobs:
  spider_task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install requests
      - run: python fetch.py
      - run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Bot"
          git add v_data_88.txt
          git commit -m "Update" || exit 0
          git push
